### ISSUE TITLE
php 5 to 8 migration

### ISSUE THREAD

**Issue by tjyang** [pnp4nagios/pnp4nagios#10]
Verify @celane's patches for php 8 and pnp4nagios.

**Comment by celane** [comment]
I think the migration to PHP 8 can be marked "done", barring random bugfixes here and there, so closing this issue.

**Comment by T100D** [comment]
> btw, we are also maintaining a pnp branch here: https://github.com/ConSol-Monitoring/pnp It works well with PHP 8.2.

Thank you so much, you all saved our printing function in php 7.4
