### ISSUE TITLE
Merge patches from different forks

### ISSUE THREAD

**Issue by tjyang** [pnp4nagios/pnp4nagios#13]
Hello @celane 
Glad to have you onboard. Write access is opened for you. 
Would you please merge your patches here ?

**Comment by tjyang** [comment]
@sni 
Certainly. Thanks for the reminding.   As shown below. IMHO we should only keep master branch.
What do you think ?

**Comment by tjyang** [comment]
@sni 
@celane 
@PVasileff 

I need to rename this repo as pnp4nagios.ToBeDeleted, and start a new fork and detach process.
This way we can work from @lingej 's last commit.

**Comment by tjyang** [comment]
https://github.com/pnp4nagios/pnp4nagios is now detached as standalone repo by github support. We can start to commit carefully, after discussion of which fork to start with ?

**Comment by tjyang** [comment]
@sni, would you please provide url for your patches ?

**Comment by sni** [comment]
here it is https://github.com/lingej/pnp4nagios/compare/master...ConSol-Monitoring:pnp:master

**Comment by tjyang** [comment]
@sni , Sorry, I decided to use @celane since it was used at my work without issue.  Please submit patch if your repo has patch chuck's missed.
