### ISSUE TITLE
Pnp4nagios not load pictures, but PDF report works fine with graphs

### ISSUE THREAD

**Issue by Q1984** [pnp4nagios/pnp4nagios#3]
Hello,

I've got empty pictures, instead of graphs. Tried several browser still the same. No errors on the apache logs.  PDF reports works well. Version 0.6.16.

![kép](https://user-images.githubusercontent.com/50952023/78183403-225a8580-7468-11ea-8502-9219bae0a8c8.png)

**Comment by 0x412e4e** [comment]
I have the same issue as well, running on CentOS 8.2.2004. Both npcd and httpd logs have no errors in them.

**Comment by 0x412e4e** [comment]
![2020-07-08 20_13_18-RE_ PNP4Nagios solution - Message (HTML)](https://user-images.githubusercontent.com/51528875/86949501-68a23d80-c157-11ea-8698-34b9ef50c28a.png)
![2020-07-08 20_13_12-RE_ PNP4Nagios solution - Message (HTML)](https://user-images.githubusercontent.com/51528875/86949504-693ad400-c157-11ea-8558-87955d135ee8.png)
![2020-07-08 20_13_05-RE_ PNP4Nagios solution - Message (HTML)](https://user-images.githubusercontent.com/51528875/86949506-69d36a80-c157-11ea-82e7-000b8fd08131.png)

Here's three things I did and now it works! Hopefully someone can find this useful.

**Comment by tjyang** [comment]
closing this issue.
