### ISSUE TITLE
get_magic_quotes_gpc() is depricated in modern php

### ISSUE THREAD

**Issue by Heliophobe** [pnp4nagios/pnp4nagios#30]
I have a fresh install of centos stream 9 and nagios core 4.4.8 running, php version 8.0.27 (installed from repos), when I followed the install instructions I get this page when I click on a graph link in nagios, which seems to indicate it is trying to use a deprecated feature:

`<h1>PNP4Nagios Environment Tests</h1>

<p>The following options are determined by "configure". If any of the tests have failed, consult the <a href="http://docs.pnp4nagios.org/pnp-0.6/install">documentation</a> for more information on how to correct the problem.</p>

<div id="tests">
<br><b>Fatal error</b>:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /usr/local/pnp4nagios/share/install.php:108
Stack trace:
#0 /usr/local/pnp4nagios/share/index.php(140): include()
#1 {main}
  thrown in <b>/usr/local/pnp4nagios/share/install.php</b> on line <b>108</b><br>

PNP4Nagios Version | pnp4nagios-0.6.26
-- | --
/usr/local/pnp4nagios
./configure
/usr/local/pnp4nagios/var/perfdata is readable.
/usr/bin/rrdtool is executable by PHP
Pass
Pass
Pass
Pass
Pass

</div>PNP4Nagios Environment Tests

The following options are determined by "configure". If any of the tests have failed, consult the [documentation](http://docs.pnp4nagios.org/pnp-0.6/install) for more information on how to correct the problem.

Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /usr/local/pnp4nagios/share/install.php:108 Stack trace: #0 /usr/local/pnp4nagios/share/index.php(140): include() #1 {main} thrown in /usr/local/pnp4nagios/share/install.php on line 108
PNP4Nagios Version 	pnp4nagios-0.6.26
Prefix 	/usr/local/pnp4nagios
Configure Arguments 	./configure
RRD Storage 	/usr/local/pnp4nagios/var/perfdata is readable.
RRDtool Binary 	/usr/bin/rrdtool is executable by PHP
PHP GD extension 	Pass
PHP function proc_open() 	Pass
PHP zlib extension 	Pass
PHP session extension 	Pass
PHP JSON extension 	Pass
PHP magic_quotes_gpc`

![image](https://github.com/pnp4nagios/pnp4nagios/assets/1926093/2559da8b-8f4b-4f83-aa00-e97a1d50ed9d)

**Comment by Heliophobe** [comment]
I circumvented this issue by editing /usr/local/pnp4nagios/share/index.php, making it fail this check automatically. I don't know why his should happen on a fresh install though.

**Comment by celane** [comment]
It happened because the "magic_quotes" stuff was commented out in the files used for an RPM-based installation (which is what I use), but neglected to clean up the other instances.  Now done, in the "testing" branch, and will be propagated to the main branch once a bit more testing is done. 

Thanks for finding this! Yes, I do focus too much on RPM installations, because that's what I use on the systems I run, so we definitely need more diversity in the installation environments to find all those bugs.
