### ISSUE TITLE
pnp4nagios on Rocky Linux 9, apache Variable 'XDG_CACHE_HOME' does not exist

### ISSUE THREAD

**Issue by agibson2** [pnp4nagios/pnp4nagios#32]
**Describe the bug**
When starting the apache service, the If statement in the apache config file that pnp4nagios uses causes an error.  It appears the If statement doesn't work because XDG_CACHE_HOME isn't defined.
`        <If "-z %{XDG_CACHE_HOME}">`
`            <IfModule mod_env.c>`
`                SetEnv XDG_CACHE_HOME /tmp/apache-fontconfig`
`            </IfModule>`
`        </If>`

**To Reproduce**
Build a src rpm from latest released (0.6.27-3) using included spec file on Rocky Linux 9
Install on Rocky Linux 9 Minimal OS install with only packages needed for nagios and pnp4nagios
Start httpd (apache)

**Expected behavior**
Expected httpd service to start.

**Screenshots**
Sep 27 17:10:29 localhost httpd[165268]: AH00526: Syntax error on line 21 of /etc/httpd/conf.d/pnp4nagios.conf:
Sep 27 17:10:29 localhost httpd[165268]: Cannot parse condition clause: Variable 'XDG_CACHE_HOME' does not exist

**Desktop (please complete the following information):**
 - NagiosCore : nagios-4.4.14-1.el9.x86_64
 - apache: httpd-2.4.53-11.el9_2.5.x86_64
 - OS: Rocky Linux 9

**Additional context**
Commenting out the <If> and </If> lines lets the httpd service start properly.
`        #<If "-z %{XDG_CACHE_HOME}">`
`            <IfModule mod_env.c>`
`                SetEnv XDG_CACHE_HOME /tmp/apache-fontconfig`
`            </IfModule>`
`        #</If>`

I still have a problem where rrdtool can't write to the /tmp/... cache directory even when giving the directory in the temp directory full uog rwx access but still digging.

And a big THANK YOU for keeping this software going.  It is still very useful.  I bet a lot of people are going to be upgrading to a new OS with CentOS 7 going EOL next year.

**Comment by celane** [comment]
The fix was in the "testing" branch, which (sorry) I'd been sitting on for too long. Now merged. 
As you comment, taking those lines out of the httpd config helps, but there's also some code added from the testing branch that sets the XDG_CACHE_HOME environment variable in the php code before calling rrd graph. 

It's just obnoxious that we have pnp4nagios -> rrd graph -> pango -> fontconfig 
that croaks if it doesn't have XDG_CACHE_HOME. Which it *does* for interactive use. But not Apache. 

So if your graphs don't appear, the relevant code is in 
pnp4nagios/share/pnp/application/models/(data.php|rrdtool.php) 

Hoping to get a release rolled out within the next week. Fingers crossed.

**Comment by agibson2** [comment]
Thanks.  I tried pulling the latest master source and building that but it looks like using the spec to build fails because the files in share/pnp/application/lib/*.php were moved.  I modified the spec to use the new .tar.gz that I created from master obviously.

I assume you are already aware of that or maybe in the middle of something and it is expected but I can submit an issue for it if you like.

	do /usr/bin/install -c -m 644  $file /home/user/rpmbuild/BUILDROOT/pnp4nagios-0.6.27-20230929.el9.x86_64/usr/share/nagios/html/pnp4nagios/application/lib; done
/usr/bin/install: cannot stat 'pnp/application/lib/*.php': No such file or directory
make[1]: *** [Makefile:64: install] Error 1
make[1]: Leaving directory '/home/user/rpmbuild/BUILD/pnp4nagios-0.6.27.20230929/share'
make: *** [Makefile:146: install] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.JHYq63 (%install)

**Comment by agibson2** [comment]
For the problem in my last post, I edited the source and removed the Install lines from the Makefile.in in the share directory that reference that pnp/application/lib share directory and that allowed it to build properly without trying to install the missing files in pnp/application/lib.  The spec file built the RPMs just fine.

After manually fixing that It does appear that the previous issue with httpd not starting is fixed by the master version of code.  I am still running into the issue where rrdtool can't write to /tmp/apache-fontconfig.  I even gave that apache-fontconfig full rwx for user, group and other as a test and that didn't help.  Still trying to figure out what is going on there.  That is my current road block.

ERROR: env XDG_CACHE_HOME (/tmp/apache-fontonfig) is not writable directory/usr/bin/rrdtool graph - --width=500 --height=100 ==start 169002646 ....

**Comment by agibson2** [comment]
Interestingly,  I separated the checks and it is the is_dir() that is failing on /tmp/apache-fontconfig.  I just removed the checks entirely in the rrdtool.php file and then after fixing an selinux denial for rrdtool to mmap of files using httpd_d context in /var/lib, The graphs appear to be working.  I don't see any files in /tmp/apache-fontconfig (created it manually for troubleshooting) and removing that directory , it doesn't get created.

Graphs appear to be working.  Is the XDG_CACHE_HOME actually used by rrdtool?  It doesn't appear to complain if the directory doesn't exist.  Maybe it us ignoring XDG_CACHE_HOME if it isn't there?

**Comment by agibson2** [comment]
I removed the other posts.  I discovered that my RPMs were not being updated to the master RPMs that a created.  After updating to the latest master RPMs,  I get the error that they are needed it seems.  I am not sure if you are working on the code and it is in a transition state or not to move those files.

Warning: require(application/lib/jsonwrapper.php): Failed to open stream: No such file or directory in /usr/share/nagios/html/pnp4nagios/index.php on line 134

Fatal error: Uncaught Error: Failed opening required 'application/lib/jsonwrapper.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/share/nagios/html/pnp4nagios/index.php:134 Stack trace: #0 {main} thrown in /usr/share/nagios/html/pnp4nagios/index.php on line 134

**Comment by celane** [comment]
I *am* working on it, but somewhat indirectly.
In that I'm using a tiny little github repository to
work out how to automate production of RPMs for
releases.  

I think I've probably made just about all of the
possible errors in doing the automated RPM builds,
and now am making some progress. 

On Mon, 02 Oct 2023 08:15:43 -0700
agibson2 ***@***.***> wrote:

> I removed the other posts.  I discovered that my RPMs were not being
> updated to the master RPMs that a created.  After updating to the
> latest master RPMs,  I get the error that they are needed it seems.
> I am not sure if you are working on the code and it is in a
> transition state or not to move those files.
> 
> Warning: require(application/lib/jsonwrapper.php): Failed to open
> stream: No such file or directory in
> /usr/share/nagios/html/pnp4nagios/index.php on line 134
> 
> Fatal error: Uncaught Error: Failed opening required
> 'application/lib/jsonwrapper.php'
> (include_path='.:/usr/share/pear:/usr/share/php') in
> /usr/share/nagios/html/pnp4nagios/index.php:134 Stack trace: #0
> {main} thrown in /usr/share/nagios/html/pnp4nagios/index.php on line
> 134
> 



-- 
Drexel University  |/             /    ·   ν ·   Chuck Lane   |D
======]－－－>－－－C－－－－－π+－－<                Disque 911  |U
Particle Physics    \             \    ~~ e+~~   215-895-1545 |N
***@***.***                    －​μ+－－+νν                 |E
