### ISSUE TITLE
Master branch has index.php dependancy for jsonwrapper.php that was removed

### ISSUE THREAD

**Issue by agibson2** [pnp4nagios/pnp4nagios#36]
**Describe the bug**
Using the latest pnp4nagios from master has a reference in the index.php that references the application/lib/jsonwrapper.php that was removed a few weeks ago.

Just commenting out that line allows pnp4nagios to get past that problem.

// JSON Wrapper used for PHP 5.1.x
//require('application/lib/jsonwrapper.php');

**Comment by mosh5382** [comment]
I experienced this issue as well.  Additionally this line appears in install.php:

`<?php require('application/lib/jsonwrapper.php');?>`

**Comment by celane** [comment]
fix in testing branch, now pulled into master.
