### ISSUE TITLE
Fresh install fails with unknown class Security

### ISSUE THREAD

**Issue by onkobu** [pnp4nagios/pnp4nagios#40]
**Describe the bug**

Class "Security" not found
file [line]:

application/controllers/system.php [58]:

**To Reproduce**
1. Get master
2. configure && make
3. config/ run apache2
4. https://<host>/pnp4nagios/graph?host=myhost.example.net

**Expected behavior**
Graphs shown

**Screenshots**
<none>

**Additional context**
It was also necessary to fix install.php@182 and wrap `& <constant>` with `defined('<constant>')`. Otherwise runtime complains about unset constant.

I also grepped through the code and found no definition of the class. Is it imported from somewhere else? Currently I'm evaluating whether Gentoo package can be switched to your fork. The current official package is broken beyond repair and does not work with current PHP (8.x).

**Comment by celane** [comment]
The "Security" class was added with commit  939cdaa.

**Comment by celane** [comment]
fix is in latest release
