### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by mosh5382** [pnp4nagios/pnp4nagios#41]
**Describe the bug**
When running "sudo make install" I receive this error:
```
for file in pnp/application/lib/*.php; \
	do /usr/bin/install -c -m 644 -o nagios -g nagios $file /usr/local/pnp4nagios/share/application/lib; done
/usr/bin/install: cannot stat 'pnp/application/lib/*.php': No such file or directory
```

**To Reproduce**
```
./configure
sudo make all
sudo make install
```

**Expected behavior**
make install will complete without issue

**Desktop (please complete the following information):**
 - NagiosCore : 4.4.14
 - OS: Arch Linux
 - Browser Chrome or Firefox
 - Version Firefox 118

**Additional context**
I was able to complete the installation by removing the following lines from pnp4nagios/share/Makefile.in

```
	for file in pnp/application/lib/*.php; \
		do $(INSTALL) -m 644 $(INSTALL_OPTS) $$file $(DESTDIR)$(DATAROOTDIR)/application/lib; done
```

**Comment by agibson2** [comment]
I did the same thing (commenting out  the lines in that Makefile.in to remove the lib/*.php) when I built an RPM from the spec file on a main snapshot a week or two ago.

**Comment by celane** [comment]
removed the offending line (since the directory referenced doesn't exit). Okay in latest release.
