### ISSUE TITLE
Optional parameter $vname declared before required parameter $unit is implicitly treated as a required parameter

### ISSUE THREAD

**Issue by mosh5382** [pnp4nagios/pnp4nagios#42]
**Describe the bug**
```
Optional parameter $vname declared before required parameter $unit is implicitly treated as a required parameter

application/helpers/rrd.php [328]
```

**To Reproduce**
Attempt to access index.php in a browser

**Expected behavior**
A graph should be shown

**Desktop (please complete the following information):**
    NagiosCore : 4.4.14
    OS: Arch Linux
    Browser Chrome or Firefox
    Version Firefox 118
   PHP 8.2.11

**Additional context**
This error seems to be related to this in PHP 8 and newer:
https://php.watch/versions/8.0/deprecate-required-param-after-optional

**Comment by celane** [comment]
fixed in latest release. Made "$unit" optional (with a default), and in any case it seems $unit isn't used.
