### ISSUE TITLE
pnp4nagios does not start

### ISSUE THREAD

**Issue by sistemmsn** [pnp4nagios/pnp4nagios#47]
**Describe the bug**
It just doesn't start and I don't understand why, the other version works without problems

this one works fine:
https://github.com/pnp4nagios/pnp4nagios/archive/refs/tags/pnp4nagios-0.6.27.tar.gz 

but I saw that they released another version and it didn't work for me
```
RUN cd /opt  && \ 
    wget https://github.com/pnp4nagios/pnp4nagios/archive/refs/tags/v0.6.27-4.tar.gz && \ 
    tar -xvzf v0.6.27-4.tar.gz  && \ 
    cd pnp4nagios-0.6.27-4 && \ 
    ./configure --prefix=/opt/pnp4nagios && \ 
    make all && \ 
    make fullinstall && \ 
    mkdir /run/nagios && \
    cp contrib/ssi/status-header.ssi /opt/nagios/share/ssi/ && \ 
    mv /opt/pnp4nagios/share/install.php /opt/pnp4nagios/share/install.php.BKP  && \ 
    wget "https://github.com/lingej/pnp-metrics-api/raw/master/application/controller/api.php" -O /opt/pnp4nagios/share/application/controllers/api.php && \
    cd /opt && rm -Rf  pnp4nagios-0.6.27-4 v0.6.27-4.tar.gz
```

**Desktop (please complete the following information):**
 - NagiosCore : 4.4.14
 - OS: Almalinux with docker
 - php: 8.0
 - images: almalinux 8.8

**Additional context**
It looks like it starts but when checking the pid it doesn't appear.

<img width="423" alt="image" src="https://github.com/pnp4nagios/pnp4nagios/assets/38023703/9336f02b-1c6f-49e6-9938-9e7e6cd05d31">

<img width="367" alt="image" src="https://github.com/pnp4nagios/pnp4nagios/assets/38023703/aecf9431-66c8-4c0c-b584-ddb428f56482">

**Comment by celane** [comment]
I'll look into this further, but since you seem to be running Almalinux, you might want to try one of the rpms built for alma.

**Comment by celane** [comment]
Looks like it might be problems with /usr/lib/systemd/system/npcd.service  and maybe /etc/sysconfig/npcd

Could you post these two files? 

The rpm-building has gotten a lot more attention for the updates (mostly because I use rpms) so the "make" installs may have gotten messed up, particularly in the installation scripts where the rpm installation diverges from the makefile installation.

**Comment by sistemmsn** [comment]
The pnp4nagios, like the nagios core I have placed inside a container, I tried to use the rpms, but it gives the same result and throws this error:
npcd is not running but subsystem locked

I imagine that when using docker, the new version depends on systemctl
<img width="366" alt="image" src="https://github.com/pnp4nagios/pnp4nagios/assets/38023703/121074a8-5206-4d7a-89a4-df530f7d29b8">


<img width="362" alt="image" src="https://github.com/pnp4nagios/pnp4nagios/assets/38023703/dbf870d0-1264-406d-98e4-e7b51f6bc32e">

**Comment by sistemmsn** [comment]
For my part, I close the case using the 4k version, I imagine that corrections will continue to be made, I appreciate the time and support, for my part I can continue testing if you need, greetings
