### ISSUE TITLE
typo pnp4nagios/share/pnp/templates.dist /check_disk.php

### ISSUE THREAD

**Issue by Punkley** [pnp4nagios/pnp4nagios#49]
**Describe the bug**
There is a typo in check_disk.php

Line 6 reads
include 'arrayfix.pnp';

should read
include 'arrayfix.php';

**Comment by celane** [comment]
This particular typo (and probably a few more) have been fixed on the "testing" branch of the code. I expect to merge with the main branch relatively soon, just working on some autoconf issues that are important for installing, but doesn't affect the working pnp code.
