### ISSUE TITLE
Popup shows only one graph for multi datasource

### ISSUE THREAD

**Issue by tiahino** [pnp4nagios/pnp4nagios#54]
For services containing multiple data sources the popup graph displays only one source. The full graph (i.e. when the extra service actions icon is clicked) displays everything as expected.

**To Reproduce**
1. Open the Service Status Details for any host
2. Hover the mouse over the Extra Service Actions icon for some service which provides more than one data source
3. A popup window opens with only one graph

**Expected behavior**
A popup should  include graphs for all data sources provided. This was the behavior through 0.6.26

**Screenshots**
![Screenshot 2024-02-13 at 4 18 36 PM](https://github.com/pnp4nagios/pnp4nagios/assets/12177728/9f1bbeab-49f3-4220-a1f1-d2ed0a4bbd54)
![Screenshot 2024-02-13 at 4 19 20 PM](https://github.com/pnp4nagios/pnp4nagios/assets/12177728/c824a2b9-a4b7-4154-a0fe-a422e7c9d541)

**Desktop (please complete the following information):**
 - NagiosCore : 4.4.9
 - OS: Rocky Linux 8.9
 - Browser Firefox, Safari, Chrome
 - Version 0.6.27-3 - 0.6.27-4k

**Additional context**
I was able to track the issue down to the following change in /share/pnp/application/controllers/system.php:
```
--- system.php	2024-02-13 22:30:52.069922116 +0000
+++ system.php.good	2024-02-13 22:18:58.809418729 +0000
@@ -68,7 +68,7 @@
         $this->view       = pnp::clean($this->input->get('view', ''));
         $this->host       = pnp::clean($this->input->get('host', null));
         $this->service    = pnp::clean($this->input->get('srv', null));
-        $this->source     = intval(pnp::clean($this->input->get('source', null)));
+        $this->source     = pnp::clean($this->input->get('source', null));
         $this->version    = pnp::clean($this->input->get('version', null));
         $this->tpl        = pnp::clean($this->input->get('tpl'));
         $this->controller = Router::$controller;
```
This change was included in the earliest release available. I do not know the reasons of singling out this particular member of the structure and neither I could explain the effect observed, but removal of intval fixes things. Please restore the former behavior.

**Comment by celane** [comment]
I just tried this, with the suggested fix, and was unable to see any pop-up at all.
(well, there's a pop-up info box that says 'perform extra service actions'). 
pnp4nagios running on Alma 9.3 (on a virtual machine), Apache, 
browser: Opera and Firefox, same results. 

Is there some Apache or Nagios config that is needed to make the pop-up appear? 
My first thought was that the browser was blocking (because I *hate* pop-ups
and keep them mostly turned off), but no, the pop-ups are allowed.

**Comment by celane** [comment]
Okay, found the documentation, and after a bit of thrashing around (mostly trying to find where the ssi file goes), it's now working with multiple graphs, as of testing branch pre-release v0.6.27-4r ... which will be used to update the main branch soon. 

First, I may put in a small update in the documentation regarding "where to put the ssi file".  For rpm-based systems, it's not TOO bad: 'rpm -q nagios -l | grep ssi'   but I'm not nearly as familiar with Debian and how to find the correct directory.
