### ISSUE TITLE
issue with PHP8

### ISSUE THREAD

**Issue by AndreaLonghitano** [pnp4nagios/pnp4nagios#65]
Hello everyone,

I'm trying to install pnp4nagios in a Azure VM with redhat 9.4
I have installed php 8.0 following also the guidelines written in the main page of Nagios.
However this is the result following the URL http://nagios_server/pnp4nagios/

![image](https://github.com/pnp4nagios/pnp4nagios/assets/44032382/903e9980-3d79-489e-b084-5263b5ead27b)

Do you know how to solve?
Thank you,
Andrea

**Comment by sistemmsn** [comment]
Basically, you already installed it, your problem is not an error but rather that in the pnp4nagios/share/install.php folder change it to

**Comment by AndreaLonghitano** [comment]
Ok @sistemmsn the error is clear since the function is deprecated in PHP 8.0. Do you know how to solve? If I remove the install.php it will not work. Is this package compatible with PHP 8.0? 
If I try to remove the install.php I will receive this message:

![image](https://github.com/pnp4nagios/pnp4nagios/assets/44032382/8267be6b-0a8d-47f7-942b-975731be39fc)

**Comment by sistemmsn** [comment]
> Ok @sistemmsn the error is clear since the function is deprecated in PHP 8.0. Do you know how to solve? If I remove the install.php it will not work. Is this package compatible with PHP 8.0? If I try to remove the install.php I will receive this message:
> 
> ![image](https://private-user-images.githubusercontent.com/44032382/338096283-8267be6b-0a8d-47f7-942b-975731be39fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzIwOTYsIm5iZiI6MTcxODAzMTc5NiwicGF0aCI6Ii80NDAzMjM4Mi8zMzgwOTYyODMtODI2N2JlNmItMGE4ZC00N2Y3LTk0MmItOTc1NzMxYmUzOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE1MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZDdkZjY2NGMyZmZlN2FlYmY1NTZmM2E5YzkzZTJiY2U0ZTFkMzc5OTE4MzBiNzIzOTYzYzU5MzNhZDkxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YwBcrjzc78wnkoFAGybKhZPQu-krl4w4iVR8yY_ecsA)

use version 8.1

**Comment by AndreaLonghitano** [comment]
> > Ok @sistemmsn the error is clear since the function is deprecated in PHP 8.0. Do you know how to solve? If I remove the install.php it will not work. Is this package compatible with PHP 8.0? If I try to remove the install.php I will receive this message:
> > ![image](https://private-user-images.githubusercontent.com/44032382/338096283-8267be6b-0a8d-47f7-942b-975731be39fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzIwOTYsIm5iZiI6MTcxODAzMTc5NiwicGF0aCI6Ii80NDAzMjM4Mi8zMzgwOTYyODMtODI2N2JlNmItMGE4ZC00N2Y3LTk0MmItOTc1NzMxYmUzOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE1MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZDdkZjY2NGMyZmZlN2FlYmY1NTZmM2E5YzkzZTJiY2U0ZTFkMzc5OTE4MzBiNzIzOTYzYzU5MzNhZDkxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YwBcrjzc78wnkoFAGybKhZPQu-krl4w4iVR8yY_ecsA)
> 
> use version 8.1

I have tried with version 8.1.29 and the error is the same. Are you sure the packet is compatible? Also this one is deprecated as shown [here](https://www.php.net/manual/en/mbstring.constants.php#constant.mb-overload-string)

**Comment by sistemmsn** [comment]
> > > Ok @sistemmsn the error is clear since the function is deprecated in PHP 8.0. Do you know how to solve? If I remove the install.php it will not work. Is this package compatible with PHP 8.0? If I try to remove the install.php I will receive this message:
> > > ![image](https://private-user-images.githubusercontent.com/44032382/338096283-8267be6b-0a8d-47f7-942b-975731be39fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzIwOTYsIm5iZiI6MTcxODAzMTc5NiwicGF0aCI6Ii80NDAzMjM4Mi8zMzgwOTYyODMtODI2N2JlNmItMGE4ZC00N2Y3LTk0MmItOTc1NzMxYmUzOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE1MDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZDdkZjY2NGMyZmZlN2FlYmY1NTZmM2E5YzkzZTJiY2U0ZTFkMzc5OTE4MzBiNzIzOTYzYzU5MzNhZDkxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YwBcrjzc78wnkoFAGybKhZPQu-krl4w4iVR8yY_ecsA)
> > 
> > 
> > use version 8.1
> 
> I have tried with version 8.1.29 and the error is the same. Are you sure the packet is compatible? Also this one is deprecated as shown [here](https://www.php.net/manual/en/mbstring.constants.php#constant.mb-overload-string)

mmm...

It's strange, something should work, something is wrong in the compilation process, I have it on alma 8.9

![image](https://github.com/pnp4nagios/pnp4nagios/assets/38023703/1558e46a-0e5c-48cf-8571-6032a7986762)

**Comment by sistemmsn** [comment]
I was testing with alma 9.4 and php 8.1.29 and something in your implementation continues to work is wrong

![image](https://github.com/pnp4nagios/pnp4nagios/assets/38023703/7baf1ca2-187d-4fe7-8e3b-364c63605124)
![image](https://github.com/pnp4nagios/pnp4nagios/assets/38023703/9d7903f2-ee75-43a5-96fc-181a408edbf6)
![image](https://github.com/pnp4nagios/pnp4nagios/assets/38023703/bcc884e3-9914-4dfa-ae90-d81b89653aec)
![image](https://github.com/pnp4nagios/pnp4nagios/assets/38023703/87337904-4e97-46a1-b0a3-df81d28f1055)

**Comment by AndreaLonghitano** [comment]
> I was testing with alma 9.4 and php 8.1.29 and something in the implementation is still working wrong
> 
> ![image](https://private-user-images.githubusercontent.com/38023703/338694969-7baf1ca2-187d-4fe7-8e3b-364c63605124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NTQsIm5iZiI6MTcxODIwODU1NCwicGF0aCI6Ii8zODAyMzcwMy8zMzg2OTQ5NjktN2JhZjFjYTItMTg3ZC00ZmU3LThlM2ItMzY0YzYzNjA1MTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZjI4MTA1M2Q0ZGNlMmRjYzk4MzYxMDRiOTJjYjk3MmEzYmQ1MDg3N2E2OGQwODVmNDJmMjQwMTliOWY1YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v9qTinHgMYtlwKyXodeHZI5QDwOJ7u0cAQBPofVoucg) ![image](https://private-user-images.githubusercontent.com/38023703/338695066-9d7903f2-ee75-43a5-96fc-181a408edbf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NTQsIm5iZiI6MTcxODIwODU1NCwicGF0aCI6Ii8zODAyMzcwMy8zMzg2OTUwNjYtOWQ3OTAzZjItZWU3NS00M2E1LTk2ZmMtMTgxYTQwOGVkYmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NzA1N2M5OWU3Njk4OGZmMjBmZTYxMGRmYzU3Yjg2MDc5ZWVmM2QyZjU5YTBkNDQwOTM4ZDQ5YjdkMTMyMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RIXiy8cXlVOIw-AcsLH_2LLodPZsG585K3-3o9kp4ys) ![image](https://private-user-images.githubusercontent.com/38023703/338695135-bcc884e3-9914-4dfa-ae90-d81b89653aec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NTQsIm5iZiI6MTcxODIwODU1NCwicGF0aCI6Ii8zODAyMzcwMy8zMzg2OTUxMzUtYmNjODg0ZTMtOTkxNC00ZGZhLWFlOTAtZDgxYjg5NjUzYWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYjRlZGY2MThkZjY2OGY2NGQ1NzJhZWMzNjc0NmI1MjE3ZDQ3ODI0MTc1OGIwYzcyYjhkM2Q3NmJhYzcxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e6BVHBZUdVpsoJRmf1iwnrcwqpV0Z_7jGEScz5F2MVw) ![image](https://private-user-images.githubusercontent.com/38023703/338695235-87337904-4e97-46a1-b0a3-df81d28f1055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NTQsIm5iZiI6MTcxODIwODU1NCwicGF0aCI6Ii8zODAyMzcwMy8zMzg2OTUyMzUtODczMzc5MDQtNGU5Ny00NmExLWIwYTMtZGY4MWQyOGYxMDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZjE3MWMyNGJmZTI3YTMzODdiYjcwOTM1YTI5M2E1MjFmMjEzMTU1ZTFiZjk3ZjAxMmZjZGIxMjQ5YWIwODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uhrf0axuWW7ytMcrpzd4O_zbYwzpW-b6w03U9enPTAw)

I check you gist documentation. There is a reference to https://github.com/russellvt/ which of course is wrong. To use your package I should use https://github.com/pnp4nagios/. Are you sure it's working with php 8.0? If yes, I can try another installation from zero.

**Comment by sistemmsn** [comment]
> > I was testing with alma 9.4 and php 8.1.29 and something in the implementation is still working wrong
> > ![image](https://private-user-images.githubusercontent.com/38023703/338694969-7baf1ca2-187d-4fe7-8e3b-364c63605124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NTQsIm5iZiI6MTcxODIwODU1NCwicGF0aCI6Ii8zODAyMzcwMy8zMzg2OTQ5NjktN2JhZjFjYTItMTg3ZC00ZmU3LThlM2ItMzY0YzYzNjA1MTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZjI4MTA1M2Q0ZGNlMmRjYzk4MzYxMDRiOTJjYjk3MmEzYmQ1MDg3N2E2OGQwODVmNDJmMjQwMTliOWY1YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v9qTinHgMYtlwKyXodeHZI5QDwOJ7u0cAQBPofVoucg) ![image](https://private-user-images.githubusercontent.com/38023703/338695066-9d7903f2-ee75-43a5-96fc-181a408edbf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NTQsIm5iZiI6MTcxODIwODU1NCwicGF0aCI6Ii8zODAyMzcwMy8zMzg2OTUwNjYtOWQ3OTAzZjItZWU3NS00M2E1LTk2ZmMtMTgxYTQwOGVkYmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NzA1N2M5OWU3Njk4OGZmMjBmZTYxMGRmYzU3Yjg2MDc5ZWVmM2QyZjU5YTBkNDQwOTM4ZDQ5YjdkMTMyMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RIXiy8cXlVOIw-AcsLH_2LLodPZsG585K3-3o9kp4ys) ![image](https://private-user-images.githubusercontent.com/38023703/338695135-bcc884e3-9914-4dfa-ae90-d81b89653aec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NTQsIm5iZiI6MTcxODIwODU1NCwicGF0aCI6Ii8zODAyMzcwMy8zMzg2OTUxMzUtYmNjODg0ZTMtOTkxNC00ZGZhLWFlOTAtZDgxYjg5NjUzYWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYjRlZGY2MThkZjY2OGY2NGQ1NzJhZWMzNjc0NmI1MjE3ZDQ3ODI0MTc1OGIwYzcyYjhkM2Q3NmJhYzcxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e6BVHBZUdVpsoJRmf1iwnrcwqpV0Z_7jGEScz5F2MVw) ![image](https://private-user-images.githubusercontent.com/38023703/338695235-87337904-4e97-46a1-b0a3-df81d28f1055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDg4NTQsIm5iZiI6MTcxODIwODU1NCwicGF0aCI6Ii8zODAyMzcwMy8zMzg2OTUyMzUtODczMzc5MDQtNGU5Ny00NmExLWIwYTMtZGY4MWQyOGYxMDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZjE3MWMyNGJmZTI3YTMzODdiYjcwOTM1YTI5M2E1MjFmMjEzMTU1ZTFiZjk3ZjAxMmZjZGIxMjQ5YWIwODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uhrf0axuWW7ytMcrpzd4O_zbYwzpW-b6w03U9enPTAw)
> 
> I check you gist documentation. There is a reference to https://github.com/russellvt/ which of course is wrong. To use your package I should use https://github.com/pnp4nagios/. Are you sure it's working with php 8.0? If yes, I can try another installation from zero.

Pnp4nagios works well for me with php8.1.29 and 8.1.28, the only difference between yours and mine is: how do you compile it because I basically make it very personalized and everything is in containers

**Comment by celane** [comment]
On Wed, 12 Jun 2024 10:50:36 -0700
sistemmsn ***@***.***> wrote:

> > > I was testing with alma 9.4 and php 8.1.29 and something in the
> > > implementation is still working wrong
> > >  
> > 
> > I check you gist documentation. There is a reference to
> > https://github.com/russellvt/ which of course is wrong. To use your
> > package I should use https://github.com/pnp4nagios/. Are you sure
> > it's working with php 8.0? If yes, I can try another installation
> > from zero.  
> 
> Pnp4nagios works well for me with php8.1.29 and 8.1.28, the only
> difference between yours and mine is: how do you compile it because I
> basically make it very personalized and everything is in containers
> 

While I tried *many* installations from zero on virtual machines, and
got the bugs worked out (I hope),
when I tried upgrading a system that had an old pnp4nagios installation
I ran into similar problems. 

Turns out there was some old code that the upgrade didn't clean out. 
Don't know if that's the problem being seen, but thought it was worth
a mention. 
-- 
Drexel University  |/             /    ·   ν ·   Chuck Lane   |D
======]－－－>－－－C－－－－－π+－－<                Disque 911  |U
Particle Physics    \             \    ~~ e+~~   215-895-1545 |N
***@***.***                    －​μ+－－+νν                 |E

**Comment by AndreaLonghitano** [comment]
> On Wed, 12 Jun 2024 10:50:36 -0700 sistemmsn ***@***.***> wrote: > > I was testing with alma 9.4 and php 8.1.29 and something in the > > implementation is still working wrong > > > > I check you gist documentation. There is a reference to > https://github.com/russellvt/ which of course is wrong. To use your > package I should use https://github.com/pnp4nagios/. Are you sure > it's working with php 8.0? If yes, I can try another installation > from zero. Pnp4nagios works well for me with php8.1.29 and 8.1.28, the only difference between yours and mine is: how do you compile it because I basically make it very personalized and everything is in containers
> While I tried *many* installations from zero on virtual machines, and got the bugs worked out (I hope), when I tried upgrading a system that had an old pnp4nagios installation I ran into similar problems. Turns out there was some old code that the upgrade didn't clean out. Don't know if that's the problem being seen, but thought it was worth a mention. -- Drexel University  |/             /    ·   ν ·   Chuck Lane   |D ======]－－－>－－－C－－－－－π+－－<                Disque 911  |U Particle Physics    \             \    ~~ e+~~   215-895-1545 |N ***@***.***      －​μ+－－+νν                 |E

I agree with you. Upgrading a system that had an old pnp4nagios may run into issues. I have installed into a new VM from scratch and the solution works also with PHP8.* version.
