### ISSUE TITLE
Error after fresh install: Call to a member function getCode() on int (/opt/pnp4nagios/lib/kohana/system/core/Kohana.php [879]:)

### ISSUE THREAD

**Issue by midi123** [pnp4nagios/pnp4nagios#69]
**Describe the bug**
After fresh install of pnp4nagios as described in https://gist.github.com/russellvt/051fa43592778a41e53cb423b791bab6 on the /pnp4nagios/index.php/graph?host=XXXXX&srv=YYYYYY page the error appears:

```
Please check the documentation for information about the following error.
Call to a member function getCode() on int

file [line]:
/opt/pnp4nagios/lib/kohana/system/core/Kohana.php [879]:

```

**To Reproduce**
1. Install pnp4nagios
2. Go to any page like: /pnp4nagios/index.php/graph?host=XXXXX&srv=YYYYYY
3. See error

**Expected behavior**
Page with graphs.

**Screenshots**
![Zrzut ekranu 2024-07-06 174750](https://github.com/pnp4nagios/pnp4nagios/assets/33291498/87ff5c5e-a4ab-4962-ba40-9567af905200)

**Desktop (please complete the following information):**
 - NagiosCore: 4.5.3
 - OS: Linux raspberrypi 6.6.31+rpt-rpi-v7 Raspbian (2024-05-29) armv7l
 - Browser: Edge
 - pnp4nagios version: pnp4nagios-0.6.26 [ 08-21-2017 ] from: https://github.com/russellvt/pnp4nagios.git
 - PHP version: PHP 8.2.7 (cli) (built: Jul 20 2023 18:02:54) (NTS)

**Comment by sistemmsn** [comment]
I think you made the wrong development, currently pnp4nagios is working correctly in its version [v0.6.27-5](https://github.com/pnp4nagios/pnp4nagios/releases/tag/v0.6.27-5) of this same project and it will install it, remove your old installation of pnp4nagios and run it again using the named version

Use php 8.1

**Comment by midi123** [comment]
Thank you @sistemmsn.
My only regret is that in the meantime I corrected the pnp4nagios code on my own ;) It took me about two hours of unnecessary work with ChatGPT. If I had known that it had already been corrected in the source you showed me :D If I had waited a few hours, the matter would have been sorted out.

**Comment by midi123** [comment]
The solution is:

edit: /share/application/controllers/popup.php and change:

```
class Popup_Controller extends System_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->template          = $this->add_view('popup');
    }
```

into:

```
class Popup_Controller extends System_Controller
{
    public $imgwidth;
    public function __construct()
    {
        parent::__construct();
        $this->template          = $this->add_view('popup');
    }
```
