### ISSUE TITLE
Automatic conversion of false to array is deprecated - check_snmp_memory.php

### ISSUE THREAD

**Issue by Toby737** [pnp4nagios/pnp4nagios#71]
**Describe the bug**
Have setup graphing for memory utilization but when you view the graph, it throws up an error.
Using the check_snmp_memory plugin.
I guess it could be due to php 8.3?

**Expected behavior**
The usual pnp4nagios graph should display.

**Host Info**
 - Nagios Core : 4.5.3
 - OS: CentOS 9
 - PHP 8.3.10

**Screenshot** 
![Screenshot 2024-08-07 093027](https://github.com/user-attachments/assets/24245b5b-46f8-4d6c-93d1-9a764df2d4e2)

**Comment by Toby737** [comment]
Closing cos I ended up just deleting that file.

**Comment by celane** [comment]
check_snmp_memory.php doesn't seem to be in the php4nagios distribution. Some old (custom?) file that didn't get updated?
