### ISSUE TITLE

magic_quotes_gpc() error

### ISSUE THREAD

**Issue by IdR3n** [pnp4nagios/pnp4nagios#75]
**Describe the bug**
Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /usr/local/pnp4nagios/share/install.php:108 Stack trace: #0 /usr/local/pnp4nagios/share/index.php(140): include() #1 {main} thrown in /usr/local/pnp4nagios/share/install.php on line 108

**To Reproduce**

**Expected behavior**

**Screenshots**
![tmp_af536b4c-ebbf-4bba-9a3a-13d23c4eb78e.png](https://github.com/user-attachments/assets/48bf84a5-2f25-4f74-b220-6af95783dcd5)

**Desktop (please complete the following information):**
 - NagiosCore : 4.5.8
 - OS: Ubuntu
 - Browser : Firefox, Microsoft edge 
 - Version 24.04 LTS

**Additional context**
I created a VM in VMware ESXi 7.0 U2 virtual machine and installed Ubuntu 24.04 LTS,

No matter what I try, I can't get rid of this error. Can you help me figure out what to do?
Notes: If I add this code to the part of the code where I get an error, it tells me that this operation is invalid for the section where I get the problem and gives the next problem, the MB_OVERLOAD_STRINGS error.
Code: 
```
<?php
if (function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc() == FALSE): ?> <td class="pass">Off</td> <?php else: $failed++ ?> 
<td class="fail">PHP <a href="http://docs.pnp4nagios.org/faq/i7">magic_quotes_gpc</a> is deprecated</td>
 
<?php endif ?>


```

**Comment by celane** [comment]
This is probably the result of leftovers from an older release.
The current install.php only has "get_magic_quotes_gpc" in a text
message that it has been removed from the code. 

On Tue, 10 Dec 2024 05:15:06 -0800
"Idris B.SARIKAYA" ***@***.***> wrote:

> Describe the bug
> Fatal error: Uncaught Error: Call to undefined function
> get_magic_quotes_gpc() in /usr/local/pnp4nagios/share/install.php:108
> Stack trace: #0 /usr/local/pnp4nagios/share/index.php(140): include()
> #1 {main} thrown in /usr/local/pnp4nagios/share/install.php on line
> 108
> 
> To Reproduce
> Steps to reproduce the behavior:
> • Go to '...'
> • Click on '....'
> • Scroll down to '....'
> • See error
> 
> Expected behavior
> A clear and concise description of what you expected to happen.
> 
> Screenshots
> tmp_af536b4c-ebbf-4bba-9a3a-13d23c4eb78e.png (view on web)
> 
> Desktop (please complete the following information):
> • NagiosCore : 4.5.8
> • OS: Ubuntu
> • Browser Firefox, Microsoft edge
> • Version 24.04 LTS
> 
> Additional context
> 
> No matter what I try, I can't get rid of this error. Can you help me
> figure out what to do? Notes: If I add this code to the part of the
> code where I get an error, it tells me that this operation is invalid
> for the section where I get the problem and gives the next problem,
> the MB_OVERLOAD_STRINGS error. Code: ``` Off PHP magic_quotes_gpc is
> deprecated
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID: ***@***.***>



-- 
Drexel University  |/             /    ·   ν ·   Chuck Lane   |D
======]－－－>－－－C－－－－－π+－－<                Disque 911  |U
Particle Physics    \             \    ~~ e+~~   215-895-1545 |N
***@***.***                    －​μ+－－+νν                 |E

**Comment by IdR3n** [comment]
@celane But I used the method you guys said to installation guide, but I'm still having this problem. What version should I download?
the installation guide I use:
https://gist.github.com/russellvt/051fa43592778a41e53cb423b791bab6

**Comment by IdR3n** [comment]
@celane I searched and downloaded the latest version 0.6.27-5, and looking at the other “issues” tickets, it seems that the download or installation is somehow different compared to 0.6.26. Can you give me a installation guide (to install from source code) to install it correctly?

**Comment by celane** [comment]
see reply in next issue.
